name: flutter_component_playground
description: "A new Flutter project, playground of flutter components"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  equatable: ^2.0.7
  flutter_svg: ^2.1.0
  formz: ^0.8.0
  http: ^1.3.0
  jiffy: ^6.3.2
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  json_annotation: ^4.9.0
  envied: ^1.1.1
  #flutter_local_notifications: ^18.0.1
  intl: ^0.19.0
  #freezed_annotation: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  flutter_widget_from_html: ^0.15.3
  logger: ^2.5.0
  yaml_edit: ^2.2.2
  go_router: ^14.8.0
  logging: ^1.3.0
  pinput: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  dart_code_linter: ^2.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  intl_utils: ^2.8.8
  #freezed: ^3.0.3
  flutter_launcher_icons: "^0.14.3"

  flutter_localizations:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.jpg"

flutter_intl:
  enabled: true
  arb_dir: lib/localization
  output_dir: lib/localization/generated
  class_name: LocalizedStrings

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf